version: '3.2'

# volumes:
#   ui_nm:

services:
      
  ui:
    build: AppFrontEnd/.
    ports:
      - "80:3000"
    volumes:
      - ./AppFrontEnd:/AppFrontEnd
      - /AppFrontEnd/node_modules/
    environment:
      NODE_ENV: development

  api:
    build: 
      context: AppApi/
      dockerfile: Dockerfile.Api
    ports:
     - "5001:5001"
    volumes:
      - ./AppApi/:/AppApi/

  model:
    build: 
      context: Models/
      dockerfile: Dockerfile
    ports:
     - "5002:5002"
    volumes:
      - ./Models/:/Models/
      